version: '2'

services:
  app:
    image: 'technaxis:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8000:8080

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AMAZON_AWS_ACCESS=ACCESS
      - AMAZON_AWS_SECRET=SECRET
      - AMAZON_AWS_REGION=us-east-1
      - AMAZON_AWS_BUCKET=bucket

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres